# Site settings
title: Max Drzewinski
description: >
  Maz Drzewinski: designer, artist, gamer
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
exclude: [Gemfile, Gemfile.lock]
theme: null

sass:
  style: compressed
